In [8]:
import torch

Nif=1
Nix=5
Niy=5

Nkx=3
Nky=3

Nox=3
Noy=3
Nof=4

s=1

input=torch.randn( Nif, Nix, Niy)
weight=torch.randn(Nif, Nof, Nkx, Nky)
output=torch.zeros(Nof, Nox, Noy)


In [14]:

for no in range(Nof):
    for y in range(Noy):
        for x in range(Nox):
            for ni in range (Nif):
                for ky in range(Nky):
                    for kx in range(Nkx):
                        output[no][x][y]+=input[ni][s*x+kx][s*y+ky] * weight[ni][no][kx][ky]
                        print("input ", input)
                        print("output ",output)
                        print("weight ",weight)

input  tensor([[[ 1.0527, -0.6420,  1.5494, -0.3188,  1.0056],
         [-0.5570,  0.5737, -0.1715, -0.4835, -1.6974],
         [ 1.1813, -1.2347, -0.7304,  2.5393, -1.7603],
         [ 0.2774, -0.1283, -0.7668, -0.5408, -0.3844],
         [-0.2483, -0.3304, -3.0573,  1.6323,  0.5578]]])
output  tensor([[[0.7103, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000]],

        [[0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000]],

        [[0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000]],

        [[0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000]]])
weight  tensor([[[[ 0.6748, -1.4934,  0.6666],
          [ 0.1876, -1.4061,  0.4958],
          [-0.5781,  0.4285,  0.0373]],

         [[ 0.6776,  0.8717, -0.1540],
          [-0.5623,  0.4181,  1.1131],
          [ 0.4570,  1.2507,  0.5136]],

         [[-0.4634,  0.7039, 

In [15]:
print(input)

tensor([[[ 1.0527, -0.6420,  1.5494, -0.3188,  1.0056],
         [-0.5570,  0.5737, -0.1715, -0.4835, -1.6974],
         [ 1.1813, -1.2347, -0.7304,  2.5393, -1.7603],
         [ 0.2774, -0.1283, -0.7668, -0.5408, -0.3844],
         [-0.2483, -0.3304, -3.0573,  1.6323,  0.5578]]])


In [17]:
print(weight)

tensor([[[[ 0.6748, -1.4934,  0.6666],
          [ 0.1876, -1.4061,  0.4958],
          [-0.5781,  0.4285,  0.0373]],

         [[ 0.6776,  0.8717, -0.1540],
          [-0.5623,  0.4181,  1.1131],
          [ 0.4570,  1.2507,  0.5136]],

         [[-0.4634,  0.7039,  1.3865],
          [-0.5330,  0.8225,  0.1034],
          [ 0.3143,  0.7347, -0.5648]],

         [[ 1.7756,  0.2459,  0.4915],
          [-0.9025, -0.0905, -0.4609],
          [-0.1199,  1.6316, -0.8984]]]])


In [16]:
print(output)

tensor([[[ 4.6659e-01, -2.3551e+00,  3.4427e+00],
         [ 4.6086e-03,  2.1008e+00, -4.9081e+00],
         [ 1.8943e+00,  1.6781e+00, -2.5449e+00]],

        [[-1.1022e+00, -1.4158e-01,  5.5997e-01],
         [-2.2719e+00,  2.2339e+00, -1.9875e+00],
         [-3.3232e+00, -5.8513e+00,  2.6973e+00]],

        [[ 1.8364e+00, -1.9097e+00,  2.6004e+00],
         [-8.7046e-01, -1.0351e+00, -7.3971e-01],
         [-1.3558e+00, -3.1127e-01, -4.6729e-01]],

        [[ 1.5026e+00, -4.5201e+00,  9.9601e+00],
         [-1.1036e+00, -8.0800e-04, -4.6223e-01],
         [ 3.7868e+00, -7.1045e+00,  1.9092e+00]]])
