In [1]:
import torch

Nif=1
Nix=5
Niy=5

Nkx=3
Nky=3

Nox=3
Noy=3
Nof=4

s=1

input=torch.randn( Nif, Nix, Niy)
weight=torch.randn(Nif, Nof, Nkx, Nky)
output=torch.zeros(Nof, Nox, Noy)


In [2]:
cycle=0

In [3]:
for no in range(Nof):
    for y in range(Noy):
        for x in range(Nox):
            for ni in range (Nif):
                for ky in range(Nky):
                    for kx in range(Nkx):
                        output[no][x][y]+=input[ni][s*x+kx][s*y+ky] * weight[ni][no][kx][ky]
                        #print("input ", input)
                        #print("output ",output)
                        #print("weight ",weight)
                        cycle+=1

In [4]:
print(cycle)

324


In [5]:
print(input)

tensor([[[-2.9378e-04,  6.3705e-01,  1.5318e+00, -1.8211e+00, -1.1400e+00],
         [ 3.2860e-03, -1.4289e+00, -6.3217e-01, -1.3336e+00, -8.0581e-01],
         [-6.0075e-01,  8.7936e-01,  1.2268e+00, -2.7594e+00,  1.0773e+00],
         [-1.2647e+00,  4.1384e-01, -1.2948e+00, -5.3020e-01,  1.6879e+00],
         [ 3.8896e-01, -2.1817e-01,  1.1991e+00,  1.6991e+00, -1.4263e-01]]])


In [6]:
print(weight)

tensor([[[[-0.3823, -2.1228, -1.3695],
          [ 2.5691,  0.5481, -0.3218],
          [-0.2962,  2.4550,  0.0549]],

         [[-0.8323, -1.1284, -0.4434],
          [ 1.0537, -2.0080,  0.9542],
          [-0.5456,  1.1781,  0.3317]],

         [[-0.0973, -0.0699, -0.4533],
          [ 1.2137, -0.2818,  0.5736],
          [-1.3787, -0.1333, -0.0278]],

         [[ 0.9722,  0.7203,  0.8753],
          [ 0.9977, -0.8187, -0.4336],
          [ 0.3250, -1.7569,  1.6287]]]])


In [7]:
print(output)

tensor([[[-1.6171, -1.9900, -4.3330],
         [ 3.7611,  4.2038,  4.6434],
         [-6.5076,  4.4645,  3.5616]],

        [[ 2.6425, -2.9099, -1.0346],
         [ 1.4098, -3.6028, 10.8916],
         [-4.5067,  3.7327,  4.2262]],

        [[-0.0179, -2.9638, -1.7122],
         [ 1.8372, -0.4567,  5.2132],
         [-3.4938,  1.7362, -2.7444]],

        [[ 3.5045, -6.5651,  6.9915],
         [-6.6773, -0.3969,  3.9952],
         [ 2.5467,  1.6155, -4.2692]]])
