## Model Architecture

### BCResNets
- **cnn_head**: `Sequential`
  - (0): `Conv2d(1, 16, kernel_size=(5, 5), stride=(2, 1), padding=(2, 2), bias=False)`
  - (1): `BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)`
  - (2): `ReLU6(inplace=True)`

- **BCBlocks**: `ModuleList`
  - (0): `ModuleList`
    - (0): `BCResBlock`
      - **f2**: `Sequential`
        - (0): `ConvBNReLU`
          - **block**: `Sequential`
            - (0): `Conv2d(16, 8, kernel_size=(1, 1), stride=(1, 1), bias=False)`
            - (1): `BatchNorm2d(8, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)`
            - (2): `ReLU6(inplace=True)`
        - (1): `ConvBNReLU`
          - **block**: `Sequential`
            - (0): `Conv2d(8, 8, kernel_size=(3, 1), stride=(1, 1), padding=(1, 0), groups=8, bias=False)`
            - (1): `SubSpectralNorm`
              - **ssnorm**: `BatchNorm2d(40, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)`
      - **avg_gpool**: `AdaptiveAvgPool2d(output_size=(1, None))`
      - **f1**: `Sequential`
        - (0): `ConvBNReLU`
          - **block**: `Sequential`
            - (0): `Conv2d(8, 8, kernel_size=(1, 3), stride=(1, 1), padding=(0, 1), groups=8, bias=False)`
            - (1): `BatchNorm2d(8, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)`
            - (2): `ReLU6(inplace=True)`
        - (1): `Conv2d(8, 8, kernel_size=(1, 1), stride=(1, 1), bias=False)`
        - (2): `Dropout2d(p=0.1, inplace=False)`

  - (1): `ModuleList`
    - (0): `BCResBlock`
      - **f2**: `Sequential`
        - (0): `ConvBNReLU`
          - **block**: `Sequential`
            - (0): `Conv2d(8, 12, kernel_size=(1, 1), stride=(1, 1), bias=False)`
            - (1): `BatchNorm2d(12, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)`
            - (2): `ReLU6(inplace=True)`
        - (1): `ConvBNReLU`
          - **block**: `Sequential`
            - (0): `Conv2d(12, 12, kernel_size=(3, 1), stride=(2, 1), padding=(1, 0), groups=12, bias=False)`
            - (1): `SubSpectralNorm`
              - **ssnorm**: `BatchNorm2d(60, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)`
      - **avg_gpool**: `AdaptiveAvgPool2d(output_size=(1, None))`
      - **f1**: `Sequential`
        - (0): `ConvBNReLU`
          - **block**: `Sequential`
            - (0): `Conv2d(12, 12, kernel_size=(1, 3), stride=(1, 1), padding=(0, 2), dilation=(1, 2), groups=12, bias=False)`
            - (1): `BatchNorm2d(12, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)`
            - (2): `ReLU6(inplace=True)`
        - (1): `Conv2d(12, 12, kernel_size=(1, 1), stride=(1, 1), bias=False)`
        - (2): `Dropout2d(p=0.1, inplace=False)`

  - (2): `ModuleList`
    - (0): `BCResBlock`
      - **f2**: `Sequential`
        - (0): `ConvBNReLU`
          - **block**: `Sequential`
            - (0): `Conv2d(12, 16, kernel_size=(1, 1), stride=(1, 1), bias=False)`
            - (1): `BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)`
            - (2): `ReLU6(inplace=True)`
        - (1): `ConvBNReLU`
          - **block**: `Sequential`
            - (0): `Conv2d(16, 16, kernel_size=(3, 1), stride=(2, 1), padding=(1, 0), groups=16, bias=False)`
            - (1): `SubSpectralNorm`
              - **ssnorm**: `BatchNorm2d(80, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)`
      - **avg_gpool**: `AdaptiveAvgPool2d(output_size=(1, None))`
      - **f1**: `Sequential`
        - (0): `ConvBNReLU`
          - **block**: `Sequential`
            - (0): `Conv2d(16, 16, kernel_size=(1, 3), stride=(1, 1), padding=(0, 4), dilation=(1, 4), groups=16, bias=False)`
            - (1): `BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)`
            - (2): `ReLU6(inplace=True)`
        - (1): `Conv2d(16, 16, kernel_size=(1, 1), stride=(1, 1), bias=False)`
        - (2): `Dropout2d(p=0.1, inplace=False)`

- **classifier**: `Sequential`
  - (0): `BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)`
  - (1): `Conv2d(16, 12, kernel_size=(1, 1), stride=(1, 1))`
  - (2): `AdaptiveAvgPool2d(output_size=1)`


In [1]:
import torch
import ast

torch.set_printoptions(profile="full")

file_path = 'sample.txt'  
with open(file_path, 'r') as file:
    data_str = file.read()

# 문자열을 리스트로 
data_list = ast.literal_eval(data_str)

tensor_data= torch.tensor(data_list).unsqueeze(0).unsqueeze(0)

print(tensor_data[:2])



tensor([[[[-1.5024e+01, -1.5433e+01, -1.3971e+01, -1.3276e+01, -1.2243e+01,
           -1.2916e+01, -1.6680e+01, -1.3429e+01, -1.3978e+01, -1.4638e+01,
           -1.3192e+01, -1.4157e+01, -1.4699e+01, -1.3988e+01, -1.4114e+01,
           -1.2885e+01, -1.2287e+01, -1.3167e+01, -1.2574e+01, -1.4251e+01,
           -1.0842e+01, -1.0151e+01, -1.1883e+01, -1.0730e+01, -1.2770e+01,
           -1.3664e+01, -1.2219e+01, -1.2478e+01, -8.5657e+00, -3.8724e+00,
           -5.7394e-01, -3.4273e+00, -3.4607e+00, -2.7950e+00, -3.0977e+00,
           -3.5455e+00, -4.1723e+00, -5.6725e+00, -5.5980e+00, -5.7865e+00,
           -6.0235e+00, -6.1740e+00, -6.5340e+00, -6.1036e+00, -6.1250e+00,
           -6.4989e+00, -5.7800e+00, -6.1998e+00, -7.2378e+00, -7.0484e+00,
           -6.4109e+00, -6.2705e+00, -6.7787e+00, -6.2875e+00, -5.5646e+00,
           -5.7100e+00, -6.0645e+00, -6.6531e+00, -7.3124e+00, -1.0362e+01,
           -1.0476e+01],
          [-1.5841e+01, -1.4938e+01, -1.2253e+01, -1.4900e+01, 

In [2]:
#cnn head
import torch.nn as nn
base_c=8
c = [
int(base_c * 2),
base_c,
int(base_c * 1.5),
base_c * 2,
base_c * 4,
    ]

x=tensor_data
head1=nn.Conv2d(1, c[0], kernel_size=5, stride=(1, 1), padding=0, bias=False) #[1, 16, 20, 61] #stride
x=head1(x)
#print('after head1')
#print(x)
#print("shape")
print(x.shape)
#print('weight')
#print(head1.weight)

head2=nn.BatchNorm2d(c[0]) #[1, 16, 20, 61]
x=head2(x)
print(x.shape)

head3=nn.ReLU6(True) #[1, 16, 20, 61]
x=head3(x)
print(x.shape)


torch.Size([1, 16, 36, 57])
torch.Size([1, 16, 36, 57])
torch.Size([1, 16, 36, 57])


In [3]:
print("Weight (gamma):", head2.weight)
print("Bias (beta):", head2.bias)
print("Running Mean:", head2.running_mean)
print("Running Var:", head2.running_var)

Weight (gamma): Parameter containing:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       requires_grad=True)
Bias (beta): Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       requires_grad=True)
Running Mean: tensor([ 0.1243, -0.3597, -0.8551,  0.1666,  0.1596,  0.0635,  0.0793, -0.8829,
         0.0639, -0.6061,  0.8314, -0.4499, -0.2044, -0.2862, -0.6976,  1.0592])
Running Var: tensor([1.2310, 2.0468, 6.1077, 1.3829, 1.6936, 1.2493, 1.3449, 5.8580, 1.0314,
        3.6620, 5.3555, 2.4303, 1.5860, 2.0384, 4.6445, 8.1818])


In [30]:
#first block
x=torch.randn([1, 16, 36, 57])
b1_f1_1=nn.Conv2d(16, 8, kernel_size=(1, 1), stride=(1, 1), bias=False) #[1, 8, 20, 61]
b1_f1_2=nn.BatchNorm2d(8, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True) #[1, 8, 20, 61]
b1_f1_3=nn.ReLU6(inplace=True) #[1, 8, 20, 61]
b1_f1_4=nn.Conv2d(8, 8, kernel_size=(3, 1), stride=(1, 1), padding=(0, 0), groups=8, bias=False) #[1, 8, 20, 61] #padding

x=b1_f1_1(x)
x=b1_f1_2(x)
x=b1_f1_3(x)
print(x.shape)
x=b1_f1_4(x)
print(x.shape)

# num_feature=8
# spec_groups=4
# b, c, h, w = x.size()
# assert h % spec_groups == 0
# x = x.view(b, c * spec_groups, h // spec_groups, w) #[1, 40, 4, 61]
# ssn = nn.BatchNorm2d(num_feature*spec_groups, affine=True) #[1, 40, 4, 61]
# x=ssn(x) #[1, 40, 4, 61]
# x = x.view(b, c, h, w) #[1, 8, 20, 61]
aux_2d_res = x #[1, 8, 20, 61]

b1_f2_1=nn.AdaptiveAvgPool2d(output_size=(1, 59)) # pooling in freq dimension [1, 8, 1, 61]
b1_f2_2=nn.Conv2d(8, 8, kernel_size=(1, 3), stride=(1, 1), padding=(0, 0), groups=8, bias=False) #[1, 8, 1, 61] #padding
b1_f2_3=nn.BatchNorm2d(8, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True) #[1, 8, 1, 61]
b1_f2_4=nn.ReLU6(inplace=True) #[1, 8, 1, 61]

x=b1_f2_1(x)
print(x.shape)
x=b1_f2_2(x)
x=b1_f2_3(x)
x=b1_f2_4(x)
print(x.shape)

b1_f2_5=nn.Conv2d(8, 8, kernel_size=(1, 1), stride=(1, 1), bias=False) #[1, 8, 1, 61]
b1_f2_6=nn.Dropout2d(p=0.1, inplace=False) #[1, 8, 1, 61]
x=b1_f2_5(x)
x=b1_f2_6(x)
print(x.shape)

x = x + aux_2d_res #[1, 8, 1, 61]+[1, 8, 20, 61] (broadcasted)

b1_f2_7=nn.ReLU6(inplace=True)
x=b1_f2_7(x) #[1, 8, 20, 61]
print(x.shape)

torch.Size([1, 8, 36, 57])
torch.Size([1, 8, 34, 57])
torch.Size([1, 8, 1, 59])
torch.Size([1, 8, 1, 57])
torch.Size([1, 8, 1, 57])
torch.Size([1, 8, 34, 57])


In [38]:
#second block
x=torch.randn([1, 8, 34, 57])

b2_f1_1=nn.Conv2d(8, 12, kernel_size=(1, 1), stride=(1, 1), bias=False) #[1, 12, 20, 61]
b2_f1_2=nn.BatchNorm2d(12, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True) #[1, 12, 20, 61]
b2_f1_3=nn.ReLU6(inplace=True) #[1, 12, 20, 61]
b2_f1_4=nn.Conv2d(12, 12, kernel_size=(3, 1), stride=(1, 1), padding=(0, 0), groups=12, bias=False) #[1, 12, 10, 61] #padding

x=b2_f1_1(x)
x=b2_f1_2(x)
x=b2_f1_3(x)
print(x.shape)
x=b2_f1_4(x)
print(x.shape)
# num_feature=12
# spec_groups=5
# b, c, h, w = x.size()
# assert h % spec_groups == 0
# x = x.view(b, c * spec_groups, h // spec_groups, w) #[1, 60, 2, 61]
# ssn = nn.BatchNorm2d(num_feature*spec_groups, affine=True) #[1, 60, 2, 61]
# x=ssn(x)
# x = x.view(b, c, h, w) #[1, 12, 10, 61]

aux_2d_res = x  #[1, 12, 10, 61]

b2_f2_1=nn.AdaptiveAvgPool2d(output_size=(1, 59)) #[1, 12, 1, 61]
b2_f2_2=nn.Conv2d(12, 12, kernel_size=(1, 3), stride=(1, 1), padding=(0, 0), groups=12, bias=False) #[1, 12, 1, 61] #padding, dilation
b2_f2_3=nn.BatchNorm2d(12, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True) #[1, 12, 1, 61]
b2_f2_4=nn.ReLU6(inplace=True) #[1, 12, 1, 61]

x=b2_f2_1(x)
print(x.shape)
x=b2_f2_2(x)
x=b2_f2_3(x)
x=b2_f2_4(x)
print(x.shape)

b2_f2_5=nn.Conv2d(12, 12, kernel_size=(1, 1), stride=(1, 1), bias=False) #[1, 12, 1, 61]
b2_f2_6=nn.Dropout2d(p=0.1, inplace=False) #[1, 12, 1, 61]
x=b2_f2_5(x)
x=b2_f2_6(x)
print(x.shape)

x = x + aux_2d_res #[1, 12, 1, 61]+[1, 12, 10, 61]
b2_f2_7=nn.ReLU6(inplace=True)
x=b2_f2_7(x)
print(x.shape)

torch.Size([1, 12, 34, 57])
torch.Size([1, 12, 32, 57])
torch.Size([1, 12, 1, 59])
torch.Size([1, 12, 1, 57])
torch.Size([1, 12, 1, 57])
torch.Size([1, 12, 32, 57])


In [42]:
x=torch.randn([1, 12, 32, 57])

#third block
b3_f1_1=nn.Conv2d(12, 16, kernel_size=(1, 1), stride=(1, 1), bias=False) #[1, 16, 10, 61]
b3_f1_2=nn.BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True) #[1, 16, 10, 61]
b3_f1_3=nn.ReLU6(inplace=True) #[1, 16, 10, 61]
b3_f1_4=nn.Conv2d(16, 16, kernel_size=(3, 1), stride=(1, 1), padding=(0, 0), groups=16, bias=False) #[1, 16, 5, 61] #stride #padding

x=b3_f1_1(x)
x=b3_f1_2(x)
x=b3_f1_3(x)
print(x.shape)

x=b3_f1_4(x)
print(x.shape)

# num_feature=16
# spec_groups=5
# b, c, h, w = x.size()
# assert h % spec_groups == 0
# x = x.view(b, c * spec_groups, h // spec_groups, w) #[1, 80, 1, 61]

# ssn = nn.BatchNorm2d(num_feature*spec_groups, affine=True) #[1, 80, 1, 61]
# x=ssn(x)

# x = x.view(b, c, h, w) #[1, 16, 5, 61]

aux_2d_res = x #[1, 16, 5, 61]

b3_f2_1=nn.AdaptiveAvgPool2d(output_size=(1, 59)) #[1, 16, 1, 61]
b3_f2_2=nn.Conv2d(16, 16, kernel_size=(1, 3), stride=(1, 1), padding=(0, 0), groups=16, bias=False) #[1, 16, 1, 61] #padding, dilation
b3_f2_3=nn.BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True) #[1, 16, 1, 61]
b3_f2_4=nn.ReLU6(inplace=True) #[1, 16, 1, 61]

x=b3_f2_1(x)
print(x.shape)

x=b3_f2_2(x)
x=b3_f2_3(x)
x=b3_f2_4(x)
print(x.shape)

b3_f2_5=nn.Conv2d(16, 16, kernel_size=(1, 1), stride=(1, 1), bias=False) #[1, 16, 1, 61]
b3_f2_6=nn.Dropout2d(p=0.1, inplace=False) #[1, 16, 1, 61]
x=b3_f2_5(x)
print(x.shape)

x=b3_f2_6(x)


x = x + aux_2d_res #[1, 16, 1, 61]+[1, 16, 5, 61]
b3_f2_7=nn.ReLU6(inplace=True) #[1, 16, 5, 61]
x=b3_f2_7(x)
print(x.shape)

torch.Size([1, 16, 32, 57])
torch.Size([1, 16, 30, 57])
torch.Size([1, 16, 1, 59])
torch.Size([1, 16, 1, 57])
torch.Size([1, 16, 1, 57])
torch.Size([1, 16, 30, 57])


In [44]:
#classifier 
x=torch.randn([1, 16, 30, 57])
c1=nn.BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True) #[1, 16, 5, 61]
c2=nn.Conv2d(16, 12, kernel_size=(1, 1), stride=(1, 1)) #[1, 12, 5, 61]
c3=nn.AdaptiveAvgPool2d(output_size=1) #[1, 12, 1, 1]
x=c1(x)
x=c2(x)
x=c3(x)
print(x.shape)

torch.Size([1, 12, 1, 1])


In [15]:
import torch.nn as nn
import torch
m = nn.AdaptiveAvgPool2d((1, 59))
input = torch.randn(1, 1, 40, 57)
output = m(input)

In [16]:
print(input)

tensor([[[[-8.7275e-01,  9.9919e-01,  8.9458e-01,  6.4842e-01, -4.6728e-01,
            2.1762e+00,  9.1239e-01,  3.2534e-01, -5.7110e-01,  1.1546e+00,
            1.3159e+00,  4.3710e-01, -1.0970e+00,  4.9172e-01,  1.3266e-01,
            1.5205e+00, -9.0264e-01,  9.5516e-01, -9.8140e-02,  3.7524e-01,
           -7.3001e-01,  1.3598e+00, -1.9550e+00, -1.6326e+00, -1.5390e+00,
            1.5870e+00, -1.3440e+00,  3.7719e-01, -3.7277e-01,  8.8575e-02,
           -9.5853e-02,  1.8650e-01, -1.7329e-01, -3.6713e-01,  9.8014e-01,
           -5.9109e-01,  1.1849e+00, -1.7266e-01,  3.2658e-01,  2.5725e-01,
            5.5246e-02,  9.2654e-02,  1.0442e+00,  1.8719e+00, -6.4980e-01,
           -3.2345e-01, -8.9926e-01, -1.3298e-01, -6.5985e-02,  3.2681e-01,
           -9.4386e-01, -2.0947e+00, -7.4186e-01,  6.7241e-01, -4.2115e-01,
           -1.0142e+00,  7.6605e-01],
          [-1.6656e+00,  1.3995e-01,  1.3637e+00,  7.5737e-01, -1.1047e+00,
           -1.5176e+00,  1.2998e+00,  6.2178e-01, 

In [25]:
print(input.shape)
print(output.shape)

torch.Size([1, 1, 40, 57])
torch.Size([1, 1, 1, 59])


In [24]:
print(output)

tensor([[[[ 0.1807,  0.0325, -0.0547, -0.0032,  0.0551,  0.1077,  0.2328,
            0.1031, -0.1179,  0.0150,  0.0153, -0.0077,  0.1868,  0.1105,
            0.1093,  0.0791, -0.1634, -0.0833, -0.1123, -0.0636, -0.0332,
           -0.1220, -0.1411, -0.2190, -0.1694,  0.0716,  0.0814,  0.0783,
            0.1308,  0.0210, -0.0102, -0.1726, -0.1344,  0.0498,  0.1882,
            0.1404,  0.0151,  0.0718, -0.0313, -0.0364,  0.0874, -0.0544,
           -0.1837, -0.0378,  0.0669,  0.1402,  0.1495,  0.0722, -0.0255,
           -0.0792,  0.0131, -0.0310, -0.1048, -0.0381,  0.2257,  0.3421,
            0.1812,  0.1106,  0.1022]]]])


In [21]:
pip install openpyxl

Note: you may need to restart the kernel to use updated packages.


In [23]:
import pandas as pd
input_reshaped = input.reshape(input.shape[2], input.shape[3])

# Convert to DataFrame
df = pd.DataFrame(input_reshaped)

# Save to Excel
excel_file = "./data/input_output.xlsx"
df.to_excel(excel_file, index=False, header=False)

